# Generated by Django 3.2 on 2022-09-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='company')),
                ('subtitle', models.TextField(max_length=200)),
                ('fblink', models.URLField(blank=True, null=True)),
                ('twlink', models.URLField(blank=True, null=True)),
                ('linkedinlink', models.URLField(blank=True, null=True)),
                ('intalink', models.URLField(blank=True, null=True)),
                ('pintrestlink', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('callus', models.CharField(max_length=50)),
                ('adress', models.TextField(max_length=200)),
            ],
        ),
    ]
