# Generated by Django 3.2 on 2022-09-11 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('image', models.ImageField(upload_to='brand', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='cateogry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('image', models.ImageField(upload_to='cateogry', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ImageField(upload_to='reviwe', verbose_name='Image')),
                ('rate', models.IntegerField(verbose_name='rate')),
                ('review_content', models.CharField(max_length=500, verbose_name='reveiwcontent')),
                ('timeofreview', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_review', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('image', models.ImageField(upload_to='items', verbose_name='Image')),
                ('flag', models.CharField(choices=[('new', 'new'), ('sold', 'sold'), ('features', 'features')], max_length=10, verbose_name='Flag')),
                ('price', models.FloatField(verbose_name='Price')),
                ('sku', models.IntegerField(verbose_name='Sku')),
                ('subtitle', models.CharField(max_length=500, verbose_name='subtitle')),
                ('vedio', models.URLField(blank=True, null=True, verbose_name='vedio')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_item', to='prouducts.brand', verbose_name='brand')),
                ('cateogry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cateogry_item', to='prouducts.cateogry', verbose_name='cateogry')),
                ('tag', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
