# Generated by Django 3.2 on 2022-09-11 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prouducts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='itemimages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='itemimages', verbose_name='Image')),
                ('items', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_item', to='prouducts.items', verbose_name='itemimage')),
            ],
        ),
    ]
