# Generated by Django 3.2 on 2022-09-11 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prouducts', '0002_itemimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='image',
        ),
    ]
