# Generated by Django 3.2 on 2022-09-24 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prouducts', '0003_remove_items_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='itemimage',
            field=models.ImageField(default='', upload_to='items', verbose_name='Image'),
            preserve_default=False,
        ),
    ]
